name: Checkov Demo

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  testing-checkov:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - run: mkdir -p path

      - name: Setup Python
        uses: actions/setup-python@v4.3.0
        with:
          python-version: 3.8

      - run: pip install checkov

      - run: checkov -version
