name: Checkov Demo

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  testing-checkov:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Checkov GitHub Action
        uses: bridgecrewio/checkov-action@v12.1347.0
        with:
          framework: dockerfile
          
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
