name: Checkov Demo

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  testing-checkov:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - run: mkdir -p path

      - name: Checkov GitHub Action
        uses: bridgecrewio/checkov-action@v12.1347.0
        with:
          framework: dockerfile
          output_format: json
          soft_fail: true
          
      - run: dir >> path/result.json
      - uses: actions/upload-artifact@v3
        with:
          name: my-artifact
          path: path/result.json
          
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
