name: Checkov Demo

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  testing-checkov:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2



      - name: Setup Python
        uses: actions/setup-python@v4.3.0
        with:
          python-version: 3.8

      - run: pip install checkov

      - run: checkov -d .  --framework dockerfile -s -o json --output-file-path . 
      
      - run: git clone https://github.com/Suraj-1999-13/Demo.git
      
      - uses: actions/upload-artifact@v3
        with:
          name: my-artifact
          path: results_json.json
